# Generated by Django 5.0.1 on 2024-05-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_image_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
