# Generated by Django 5.0.1 on 2024-06-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_new_arrival'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_new_arrival',
            old_name='new_arrival_digital',
            new_name='digital',
        ),
        migrations.RenameField(
            model_name='product_new_arrival',
            old_name='new_arrival_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product_new_arrival',
            old_name='new_arrival_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product_new_arrival',
            old_name='new_arrival_price',
            new_name='price',
        ),
    ]
