# Generated by Django 5.0.1 on 2024-06-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_new_arrival_digital_product_new_arrival_digital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Product_new_arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product_new_arrival'),
        ),
    ]
